version: "3.9"
services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - PORT=${PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}

  redis:
    image: "redis:alpine"